### ISSUE TITLE
Startup parameters

### ISSUE THREAD

**Issue by matteobaccan** [kolchagov/java-crud-api#13]
Hi

I have seen that CrudApiHandler manages the startup of the project.
At the moment all the parameters are hardcoded inside the code of the project.
To have a new startup I need to write an alternative Handler with different driver/parameters/: this is not a problem

But I think that a configurable startup may help to have a better product
For example

java -jar server.jar -host 10.10.7.14 -port 1234 -datasource ORACLE -user foo -password bar 

Can I produce a PR with this modification to default CrudApiHandler ?

ciao
matteo

**Comment by kolchagov** [comment]
Hi Matteo,
you can go ahead and add parameters. Currently server primarily used as an example, but it can be also used as full-featured product. 
Jetty is a powerful server capable of hadling multiple requests with ease.
In my projects I use Tomcat and I usually add this project as a library, providing me an easy and effective REST service to databases.

Having configurable parameters can widen the project usage as a stand-alone app, so I’m 100% with you.

Thank you
