### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by matteobaccan** [kolchagov/java-crud-api#7]
Hi

I have checked the code and the project and I have seen that use the JDK 7 implementation.

The last Jdk 7 public release is on April 14, 2015, end of support is July 2022 

I think that a little switch to JDK 8 TLS (or better 11 TLS) may improve the quality of the code and use some new construct of the language.

What your opinion about this?

I have made some little code review in this direction, that are not applicable to JDK 7.

For more info about the end of update and end of support https://en.wikipedia.org/wiki/Java_version_history

ciao
matteo baccan

**Comment by mevdschee** [comment]
Hi Matto,

Thank you for your message.

>What your opinion about this?

I agree with you, the project needs some maintenance.

Kind regards,

Maurits

**Comment by kolchagov** [comment]
Hi Matto,
the project is fully comaptible with Java 8 and Tomcat 9.
I’ve used it in several Java8 projects and it’s stable in production mode. If you have any issues, please share them with us.

Regards,
I.Kolchagov

**Comment by matteobaccan** [comment]
Hi

it's funny to read Matto and not Matteo :) In Italian means crazy ;)

I know that the project works, but (for example) in pom.xml there are many old dependencies related to jdk7, and the end of support of this JDK is not so far.

You think to maintain this compatibility or upgrade to a newer JDK for use of new dependence and new language construct?

I don't want to say to you the project doesn't work, I want to know if there is in the roadmap a JDK update

ciao
matteo

**Comment by kolchagov** [comment]
My appoliges Matteo,
about the typo - it’s not intentional, I’ve just follwed Maurits’s answer.
About dependencies: they aren’t “bound" to jdk7 as java 8 happily executes jdk7 binary code. These dependencies are selected for their proven stabilty and robustness.
Primary goal was to keep jdk7 compatibility, but it’s no longer a priority. As jdk7 phases out, any security patches of declared dependencies requiring jdk8 code or binary format will drop jdk 7 support immediately.
Once again - project is fully java 8 binary compatible (and it’s currently used with java 8).

Best regards.

**Comment by matteobaccan** [comment]
Hi

don't worry about the typo :)
Ok, now it's more clear your opinion.

I have a few little patches to put in a PR. I downgrade my compiler to JDK 7 and check if pass test

Thank you for your response

ciao
matteo

**Comment by kolchagov** [comment]
Just a second note: don’t “downgrade” compiler - use Java 8 mode and it’ll work just fine
:)

**Comment by matteobaccan** [comment]
Hi

It's only for be sure to don't introduce dependences or use methods that are not inside jdk7.

Ciao
Matteo

**Comment by kolchagov** [comment]
No, just the opposite - you can use all the Java 8 code style + libraries (labdas, streams etc.)  in your code. 
The application will run just fine using JRE 8
So this project is not limiting you in any way to use the modern java language.

BUT if you really insist on JDK7 compatibility though - what you’we written is totally true. Enable Java 7 compiler mode, use appropriate code style and methods and you’ll end up with Java 7 compatible binary, if that’s what you wish.

Regards

**Comment by matteobaccan** [comment]
Hi

I wants only submit a PR that respect current code style and implementation 
I have analyzed the code for quality issues and I don't want to break any standard

Thank you for your response: I'll open some PRs in next days

Ciao
Matteo

**Comment by matteobaccan** [comment]
Hi

I have tried to build in JDK 7 without problems. The only problem is on tests that use Jetty in a version build with JDK 8.

Now I open some PRs with a stylistic cleanup.

ciao
matteo

**Comment by kolchagov** [comment]
That's because Jetty that has been used originally had a serious security
flaw and has been replaced.

:)

**Comment by matteobaccan** [comment]
Hi

I have seen that also this release has some CVE solved in the new 9.x release. For example this:

https://github.com/eclipse/jetty.project/security/advisories/GHSA-26vr-8j45-3r4w

Can I update the pom.xml of this project to the last minor version of used dependencies and submit a PR, or you think it's not important at the moment?

I don't want to produce a PR that will be rejected ;) 

ciao
matteo

**Comment by kolchagov** [comment]
Yes, you can update the pom too
